version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    image: maayanlab/sc2dat:0.0.11
    x-kubernetes:
      imagePullPolicy: IfNotPresent
      annotations:
        maayanlab.cloud/ingress: ${APPYTER_PUBLIC_URL}
    environment:
      - APPYTER_PUBLIC_URL=${APPYTER_PUBLIC_URL}
      - APPYTER_DATA_DIR=s3://${MINIO_BUCKET}/#?key=${MINIO_ACCESS_KEY}&secret=${MINIO_SECRET_KEY}
      - APPYTER_EXECUTOR=kube::maayanlab/sc2dat:0.0.9#?namespace=ct2targets&env.PLAYWRIGHT_BROWSERS_PATH=/ms-playwright&resources.requests.memory=8Gi
      - APPYTER_PROFILE=bootstrap
      - APPYTER_EXTRAS=${APPYTER_EXTRAS}
      - APPYTER_DEBUG=false
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - 5000:80

x-kubernetes:
  name: ct2targets
  namespace: ct2targets